version: "3"

services:
  zippy:
    image: zippy-make
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    cap_add:
      - "NET_ADMIN"
      - "SYS_ADMIN"
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - "../resources/:/var/local/zippy/resources/"
      - "./Makefile:/app/Makefile"
